# frozen_string_literal: true

require 'rails/generators'
require 'rails/generators/active_record'
require_relative '../generator_helpers'

module RubyLLM
  module Generators
    # Upgrades the schema generated by RubyLLM 1.16 to RubyLLM 2.0.
    class UpgradeGenerator < Rails::Generators::Base
      include Rails::Generators::Migration
      include RubyLLM::Generators::GeneratorHelpers

      MODEL_MAPPING_DEFAULTS = {
        chat: 'Chat',
        message: 'Message',
        model: 'Model',
        tool_call: 'ToolCall'
      }.freeze
      MODEL_MAPPING_TYPES = MODEL_MAPPING_DEFAULTS.keys.map(&:to_s).freeze

      namespace 'ruby_llm:upgrade'
      source_root File.expand_path('templates', __dir__)

      argument :model_mappings,
               type: :array,
               default: [],
               banner: 'chat:ChatName message:MessageName model:ModelName tool_call:ToolCallName'

      desc 'Upgrades a RubyLLM 1.16 Rails schema to 2.0'

      def self.next_migration_number(dirname)
        ::ActiveRecord::Generators::Base.next_migration_number(dirname)
      end

      def create_migration_files
        parse_model_mappings(allowed_types: MODEL_MAPPING_TYPES, defaults: MODEL_MAPPING_DEFAULTS)
        say_status :models, resolved_model_mappings

        migration_template 'prepare_v2_upgrade.rb.tt',
                           'db/migrate/prepare_ruby_llm_v2_upgrade.rb'
        migration_template 'backfill_v2_data.rb.tt',
                           'db/migrate/backfill_ruby_llm_v2_data.rb'
        migration_template 'finish_v2_upgrade.rb.tt',
                           'db/migrate/finish_ruby_llm_v2_upgrade.rb'
      end

      def show_next_steps
        say_status :success, 'Upgrade prepared!', :green
        say <<~INSTRUCTIONS

          These migrations expect the schema generated by RubyLLM 1.16. They move
          RubyLLM's model and tool-call records, preserve message content and usage,
          and remove the 1.x columns that 2.0 no longer reads.

          Next steps:
          1. Review the generated migrations
          2. Rehearse them on a recent production snapshot
          3. Stop processes that write chats, then run: bin/rails db:migrate
          4. Run: bin/rails ruby_llm:load_models
          5. Keep only the current declarations in your application models:
             #{chat_model_path}: #{acts_as_chat_declaration}
             #{message_model_path}: #{acts_as_message_declaration}
          6. Remove the 1.x model and tool-call classes, config.model_registry_class,
             and config.use_new_acts_as
          7. Update 1.x API calls using the upgrade guide

          Full upgrade guide:
             https://rubyllm.com/upgrading/

        INSTRUCTIONS
      end

      private

      def prepare_migration_class_name = 'prepare_ruby_llm_v2_upgrade'.camelize
      def backfill_migration_class_name = 'backfill_ruby_llm_v2_data'.camelize
      def finish_migration_class_name = 'finish_ruby_llm_v2_upgrade'.camelize

      def resolved_model_mappings
        @model_names.map do |type, model_name|
          "#{type}:#{model_name} -> #{table_name_for(model_name)}"
        end.join(', ')
      end

      def v1_model_name(type)
        @model_names.fetch(type)
      end

      def v1_model_table_name = table_name_for(v1_model_name(:model))
      def v1_tool_call_table_name = table_name_for(v1_model_name(:tool_call))
      def v1_model_foreign_key = "#{v1_model_table_name.singularize}_id"
      def v1_tool_call_foreign_key = "#{v1_tool_call_table_name.singularize}_id"
      def message_foreign_key = "#{message_table_name.singularize}_id"
      def chat_foreign_key = "#{chat_table_name.singularize}_id"

      def chat_model_path
        "app/models/#{chat_model_name.underscore}.rb"
      end

      def message_model_path
        "app/models/#{message_model_name.underscore}.rb"
      end
    end
  end
end
