# frozen_string_literal: true

require 'rails/generators'
require 'rails/generators/active_record'
require_relative '../generator_helpers'

module RubyLLM
  module Generators
    # Upgrades the schema generated by RubyLLM 1.16 to RubyLLM 2.0.
    class UpgradeGenerator < Rails::Generators::Base
      include Rails::Generators::Migration
      include RubyLLM::Generators::GeneratorHelpers

      MODEL_MAPPING_DEFAULTS = {
        chat: 'Chat',
        message: 'Message',
        model: 'Model',
        tool_call: 'ToolCall'
      }.freeze
      MODEL_MAPPING_TYPES = MODEL_MAPPING_DEFAULTS.keys.map(&:to_s).freeze

      namespace 'ruby_llm:upgrade'
      source_root File.expand_path('templates', __dir__)

      class_option :phase, type: :string, enum: %w[prepare backfill finish cleanup],
                           desc: 'Generate one upgrade phase; cleanup runs in a later deployment'

      argument :model_mappings,
               type: :array,
               default: [],
               banner: 'chat:ChatName message:MessageName model:ModelName tool_call:ToolCallName'

      desc 'Upgrades a RubyLLM 1.16 Rails schema to 2.0'

      def self.next_migration_number(dirname)
        ::ActiveRecord::Generators::Base.next_migration_number(dirname)
      end

      def create_migration_files
        parse_model_mappings(allowed_types: MODEL_MAPPING_TYPES, defaults: MODEL_MAPPING_DEFAULTS)
        say_status :models, resolved_model_mappings

        phases = options[:phase] ? [options[:phase]] : %w[prepare backfill finish]
        phases.each do |phase|
          template = phase == 'backfill' ? 'backfill_v2_data' : "#{phase}_v2_upgrade"
          migration = phase == 'backfill' ? 'backfill_ruby_llm_v2_data' : "#{phase}_ruby_llm_v2_upgrade"
          migration_template "#{template}.rb.tt", "db/migrate/#{migration}.rb"
        end
      end

      def show_next_steps
        say_status :success, 'Upgrade prepared!', :green
        say <<~INSTRUCTIONS

          These migrations expect the schema generated by RubyLLM 1.16. They move
          RubyLLM's model and tool-call records, preserve message content and usage,
          and retain the 1.x message columns until a later cleanup deployment.

          Next steps:
          1. Review the generated migrations
          2. Rehearse them on a recent production snapshot
          3. Stop affected web processes, workers, scheduled jobs, and retries
          4. Run preparation, backfill, and finish before reopening traffic
          5. Run: bin/rails ruby_llm:load_models
          6. Keep only the current declarations in your application models:
             #{chat_model_path}: #{acts_as_chat_declaration}
             #{message_model_path}: #{acts_as_message_declaration}
          7. Remove the 1.x model and tool-call classes, config.model_registry_class,
             and config.use_new_acts_as
          8. Update 1.x API calls using the upgrade guide

          Generate one phase with --phase prepare, backfill, or finish when the
          backfill needs to run outside your deployment's release phase.
          After verifying the upgrade, generate --phase cleanup in a later release.
          Pass the same model mappings to every invocation.

          The migrations are irreversible. Retained columns do not make a code
          rollback safe; recovery requires the previous database and application.

          Full upgrade guide:
             https://rubyllm.com/next/upgrading/

        INSTRUCTIONS
      end

      private

      def prepare_migration_class_name = 'prepare_ruby_llm_v2_upgrade'.camelize
      def backfill_migration_class_name = 'backfill_ruby_llm_v2_data'.camelize
      def finish_migration_class_name = 'finish_ruby_llm_v2_upgrade'.camelize
      def cleanup_migration_class_name = 'cleanup_ruby_llm_v2_upgrade'.camelize

      def resolved_model_mappings
        @model_names.map do |type, model_name|
          "#{type}:#{model_name} -> #{table_name_for(model_name)}"
        end.join(', ')
      end

      def v1_model_name(type)
        @model_names.fetch(type)
      end

      def v1_model_table_name = table_name_for(v1_model_name(:model))
      def v1_tool_call_table_name = table_name_for(v1_model_name(:tool_call))
      def v1_model_foreign_key = "#{v1_model_table_name.singularize}_id"
      def v1_tool_call_foreign_key = "#{v1_tool_call_table_name.singularize}_id"
      def message_foreign_key = "#{message_table_name.singularize}_id"
      def chat_foreign_key = "#{chat_table_name.singularize}_id"

      def chat_model_path
        "app/models/#{chat_model_name.underscore}.rb"
      end

      def message_model_path
        "app/models/#{message_model_name.underscore}.rb"
      end
    end
  end
end
