plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - docs/**/*
    - vendor/**/*
    - gemfiles/**/*
    - lib/generators/**/templates/**/*
  SuggestExtensions: false

Metrics/ClassLength:
  Max: 550
Metrics/AbcSize:
  Max: 80
Metrics/CyclomaticComplexity:
  Max: 25
Metrics/MethodLength:
  Max: 80
  CountAsOne:
    - array
    - hash
    - heredoc
Metrics/ModuleLength:
  Max: 550
Performance/CollectionLiteralInLoop:
  Exclude:
    - spec/**/*
Performance/RedundantBlockCall:
  Enabled: false # TODO: temporarily disabled to avoid potential breaking change
Performance/StringInclude:
  Exclude:
    - lib/ruby_llm/providers/**/capabilities.rb
Performance/UnfreezeString:
  Exclude:
    - spec/**/*
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/LeakyLocalVariable:
  Enabled: false
