blank_issues_enabled: false
contact_links:
  - name: 💬 Ask Questions
    url: https://github.com/crmne/ruby_llm/discussions
    about: Questions about using RubyLLM, implementation approaches, or general discussion
  - name: 📖 Documentation
    url: https://rubyllm.com
    about: Check the docs first - guides and examples
  - name: 🚀 Priority Development
    url: mailto:carmine@paolino.work
    about: Need a feature implemented quickly? Paid development available