# frozen_string_literal: true

require 'spec_helper'
require 'generators/ruby_llm/upgrade/upgrade_generator'
require_relative '../../support/generator_test_helpers'

RSpec.describe 'RubyLLM upgrade generator', :generator, type: :generator do # rubocop:disable RSpec/DescribeClass
  include GeneratorTestHelpers

  describe 'model mappings' do
    it 'accepts only the four application models generated by RubyLLM 1.16' do
      invalid_mappings = [
        ['mesage:Message'],
        ['message:'],
        ['batch:Batch'],
        ['chat:Chat', 'chat:Conversation']
      ]

      invalid_mappings.each do |mappings|
        generator = RubyLLM::Generators::UpgradeGenerator.new(mappings)

        expect do
          generator.parse_model_mappings(
            allowed_types: RubyLLM::Generators::UpgradeGenerator::MODEL_MAPPING_TYPES,
            defaults: RubyLLM::Generators::UpgradeGenerator::MODEL_MAPPING_DEFAULTS
          )
        end.to raise_error(Thor::Error)
      end
    end
  end

  describe 'with default model names' do
    let(:app_name) { 'test_upgrade_generator_default' }
    let(:app_path) { File.join(Dir.tmpdir, app_name) }

    before(:all) do # rubocop:disable RSpec/BeforeAfterAll
      create_upgrade_app('test_upgrade_generator_default', 'upgrade_generators_default_template.rb')
    end

    after(:all) do # rubocop:disable RSpec/BeforeAfterAll
      GeneratorTestHelpers.cleanup_test_app(File.join(Dir.tmpdir, 'test_upgrade_generator_default'))
    end

    it 'generates three focused migrations' do
      within_test_app(app_path) do
        prepare = migration_source('prepare_ruby_llm_v2_upgrade')
        backfill = migration_source('backfill_ruby_llm_v2_data')
        finish = migration_source('finish_ruby_llm_v2_upgrade')

        expect(prepare).to include('move_table(:models, :ruby_llm_models)')
        expect(prepare).to include('move_table(:tool_calls, :ruby_llm_tool_calls)')
        expect(prepare).to include('disable_ddl_transaction!')
        expect(prepare).to include('create_table :ruby_llm_usages')
        expect(prepare).to include('create_table :ruby_llm_batches')
        expect(backfill).to include('backfill_message_content')
        expect(backfill).to include('backfill_tool_results')
        expect(backfill).to include('backfill_usages')
        expect(backfill).to include('PROGRESS_TABLE = :ruby_llm_v2_backfills')
        expect(backfill).to include('with_upgrade_safety { yield range }')
        expect(finish).to include('verify_completed_backfills')
        expect(finish).to include('content_raw input_tokens output_tokens')
      end
    end

    it 'moves the RubyLLM 1.16 records into the 2.0 schema' do
      within_test_app(app_path) do
        success, output = run_rails_runner(v1_schema_and_records)
        expect(success).to be(true), output

        output, status = GeneratorTestHelpers.run_command(rails_env, %w[bundle exec rails db:migrate], chdir: Dir.pwd)
        expect(status.success?).to be(true), output

        success, output = run_rails_runner(verify_upgraded_records)
        expect(success).to be(true), output
      end
    end
  end

  describe 'with custom model mappings' do
    let(:app_name) { 'test_upgrade_generator_custom_mappings' }
    let(:app_path) { File.join(Dir.tmpdir, app_name) }

    before(:all) do # rubocop:disable RSpec/BeforeAfterAll
      create_upgrade_app('test_upgrade_generator_custom_mappings', 'upgrade_generators_custom_mappings_template.rb')
    end

    after(:all) do # rubocop:disable RSpec/BeforeAfterAll
      GeneratorTestHelpers.cleanup_test_app(File.join(Dir.tmpdir, 'test_upgrade_generator_custom_mappings'))
    end

    it 'targets the mapped 1.16 tables and honors application acronyms' do
      within_test_app(app_path) do
        prepare = migration_source('prepare_ruby_llm_v2_upgrade')
        backfill = migration_source('backfill_ruby_llm_v2_data')

        expect(prepare).to include('class PrepareRubyLLMV2Upgrade')
        expect(prepare).to include('move_table(:ai_llm_models, :ruby_llm_models)')
        expect(prepare).to include('move_table(:ai_chat_tool_calls, :ruby_llm_tool_calls)')
        expect(prepare).to include('first_existing_column(table, :ai_llm_model_id, :ruby_llm_model_id)')
        expect(prepare).to include('legacy_message_column = :ai_chat_message_id')
        expect(backfill).to include("connection.quote('AI::Chat')")
        expect(backfill).to include("connection.quote('AI::Chat::Message')")
      end
    end
  end

  def create_upgrade_app(name, template)
    path = File.join(Dir.tmpdir, name)
    GeneratorTestHelpers.cleanup_test_app(path)
    GeneratorTestHelpers.create_test_app(
      name,
      template:,
      template_path: File.expand_path('../../fixtures/templates', __dir__)
    )
  end

  def migration_source(name)
    File.read(Dir.glob("db/migrate/*_#{name}.rb").sole)
  end

  def rails_env
    {
      'BUNDLE_GEMFILE' => ENV.fetch('BUNDLE_GEMFILE'),
      'BUNDLE_IGNORE_CONFIG' => '1',
      'OPENAI_API_KEY' => ENV.fetch('OPENAI_API_KEY', 'test')
    }
  end

  def v1_schema_and_records
    <<~RUBY
      ActiveRecord::Schema.define do
        create_table :models do |t|
          t.string :model_id, null: false
          t.string :name, null: false
          t.string :provider, null: false
          t.string :family
          t.datetime :model_created_at
          t.integer :context_window
          t.integer :max_output_tokens
          t.date :knowledge_cutoff
          t.json :modalities, default: {}
          t.json :capabilities, default: []
          t.json :pricing, default: {}
          t.json :metadata, default: {}
          t.timestamps
          t.index [:provider, :model_id], unique: true
          t.index :provider
          t.index :family
        end

        create_table :chats do |t|
          t.timestamps
        end

        create_table :messages do |t|
          t.string :role, null: false
          t.text :content
          t.json :content_raw
          t.text :thinking_text
          t.text :thinking_signature
          t.integer :thinking_tokens
          t.integer :input_tokens
          t.integer :output_tokens
          t.integer :cached_tokens
          t.integer :cache_creation_tokens
          t.timestamps
          t.index :role
        end

        create_table :tool_calls do |t|
          t.string :tool_call_id, null: false
          t.string :name, null: false
          t.text :thought_signature
          t.json :arguments, default: {}
          t.timestamps
          t.index :tool_call_id, unique: true
          t.index :name
        end

        add_reference :chats, :model, foreign_key: true
        add_reference :tool_calls, :message, null: false, foreign_key: true
        add_reference :messages, :chat, null: false, foreign_key: true
        add_reference :messages, :model, foreign_key: true
        add_reference :messages, :tool_call, foreign_key: true
      end

      now = Time.current
      model = Class.new(ActiveRecord::Base) { self.table_name = 'models' }
      chat = Class.new(ActiveRecord::Base) { self.table_name = 'chats' }
      message = Class.new(ActiveRecord::Base) { self.table_name = 'messages' }
      tool_call = Class.new(ActiveRecord::Base) { self.table_name = 'tool_calls' }

      model.create!(id: 1, model_id: 'gpt-1.16', name: 'GPT 1.16', provider: 'openai',
                    modalities: {}, capabilities: [], pricing: {}, metadata: {}, created_at: now, updated_at: now)
      chat.create!(id: 1, model_id: 1, created_at: now, updated_at: now)
      message.create!(id: 1, chat_id: 1, model_id: 1, role: 'assistant', content_raw: {answer: 42},
                      input_tokens: 12, output_tokens: 3, cached_tokens: 4, cache_creation_tokens: 2,
                      thinking_tokens: 1, created_at: now, updated_at: now)
      message.create!(id: 3, chat_id: 1, role: 'assistant', content: 'Done', input_tokens: 5,
                      output_tokens: 2, created_at: now, updated_at: now)
      tool_call.create!(id: 1, message_id: 1, tool_call_id: 'call_1', name: 'calculator',
                        arguments: {expression: '6 * 7'}, created_at: now, updated_at: now)
      message.create!(id: 2, chat_id: 1, model_id: 1, role: 'tool', content: '42',
                      tool_call_id: 1, created_at: now, updated_at: now)
    RUBY
  end

  def verify_upgraded_records
    <<~RUBY
      connection = ActiveRecord::Base.connection
      model = connection.select_one('SELECT * FROM ruby_llm_models WHERE id = 1')
      chat = connection.select_one('SELECT * FROM chats WHERE id = 1')
      message = connection.select_one('SELECT * FROM messages WHERE id = 1')
      tool_call = connection.select_one('SELECT * FROM ruby_llm_tool_calls WHERE id = 1')
      usages = connection.select_all('SELECT * FROM ruby_llm_usages ORDER BY message_id').to_a
      columns = connection.columns(:messages).map(&:name)

      ok = model['model_id'] == 'gpt-1.16' &&
           chat['ruby_llm_model_id'].to_i == 1 &&
           JSON.parse(message['content']) == {'answer' => 42} &&
           JSON.parse(message['raw_content']) == {'answer' => 42} &&
           tool_call['message_type'] == 'Message' &&
           tool_call['message_id'].to_i == 1 &&
           tool_call['result_type'] == 'Message' &&
           tool_call['result_id'].to_i == 2 &&
           usages.size == 2 &&
           usages.first['provider'] == 'openai' &&
           usages.first['model'] == 'gpt-1.16' &&
           usages.first['cache_read_tokens'].to_i == 4 &&
           usages.first['cache_write_tokens'].to_i == 2 &&
           usages.last['message_id'].to_i == 3 &&
           (columns & %w[content_raw model_id tool_call_id input_tokens output_tokens
                          cached_tokens cache_creation_tokens thinking_tokens]).empty? &&
           connection.table_exists?(:ruby_llm_batches) &&
           !connection.table_exists?(:models) &&
           !connection.table_exists?(:tool_calls)
      exit(ok ? 0 : 1)
    RUBY
  end
end
