// RubyLLM Tour v7: builds the "tired vs wired" score for the RubyLLM tour video (v7) in Bitwig Studio.
//
// GENERATED by music-v7/score.py from the video's cue sheet (video/v7/v7-cues.md).
// Edit score.py (or this template, music-v7/bitwig/template.control.js) and
// regenerate; don't edit the generated script by hand.
//
// Add it under Settings > Controllers > Add controller > Carmine > RubyLLM Tour v7.
// It does nothing until you press one of its buttons, which sit under the
// controller in Settings > Controllers ("RubyLLM Tour v7"), and acts on the open
// project:
//
//   Build     tempo and groove, return tracks, instrument tracks with their
//             presets and inserts, colours, faders, pans and sends, master glue,
//             one launcher clip per part in scene 1, and a cue marker per
//             scene. Safe to press again: tracks, devices and markers it finds
//             by name are reused, and clips are rewritten. Every clip is set to
//             the score's full length, read back, and retried.
//   Lengths   reports each scene-1 clip's length ("Keys: 304 beats (76 bars)").
//   Record    records scene 1 into the arranger from bar 1 and stops after bar 76.
//   Stop      stops the transport and disarms arranger record (a safety net).
//
// Every step is logged to the Controller Script Console (Settings >
// Controllers, the console icon on this controller); lines start with
// "[RubyLLM Tour v7]". The version shows in the first popup, so you can tell
// which script Bitwig has loaded.

loadAPI(25);
host.setShouldFailOnDeprecatedUse(false);

var SCORE = /*@SCORE@*/null;

var VERSION = "1.0 (RubyLLM tour v7, tired vs wired)";
host.defineController(SCORE.vendor, SCORE.title, "1.0", SCORE.uuid, "Carmine Paolino");
host.defineMidiPorts(0, 0);

var TAG = "[" + SCORE.title + "] ";
var MAX_TRACKS = 64, MAX_FX = 8, MAX_SENDS = 8, MAX_DEVICES = 8, MAX_MARKERS = 64, MAX_MASTER_DEVICES = 16, KEYS = 128;
var POLL_MS = 50;

var app, transport, groove, arranger, markers, trackBank, fxBank, master, masterDevices, sceneBank, clip, clipTrack;
var trackDevices = [], fxDevices = [];
var running = false;
var noteStarts = {};
var noteStartCount = 0;
var lengthSeen = false;

function log(s) { host.println(TAG + s); }
function say(s) { log(s); host.showPopupNotification(SCORE.title + ": " + s); }

function init() {
  app = host.createApplication();
  transport = host.createTransport();
  groove = host.createGroove();
  arranger = host.createArranger();
  markers = arranger.createCueMarkerBank(MAX_MARKERS);
  trackBank = host.createMainTrackBank(MAX_TRACKS, MAX_SENDS, 1);
  fxBank = host.createEffectTrackBank(MAX_FX, 1);
  master = host.createMasterTrack(0);
  masterDevices = master.createDeviceBank(MAX_MASTER_DEVICES);
  sceneBank = trackBank.sceneBank();
  clip = host.createLauncherCursorClip(steps(), KEYS);
  clipTrack = clip.getTrack();

  transport.tempo().value().markInterested();
  transport.isPlaying().markInterested();
  transport.playPosition().markInterested();
  transport.isArrangerRecordEnabled().markInterested();
  transport.preRoll().markInterested();
  var gp = [groove.getEnabled(), groove.getShuffleRate(), groove.getShuffleAmount()];
  for (var g = 0; g < gp.length; g++) { gp[g].markInterested(); gp[g].displayedValue().markInterested(); }

  var i, j;
  for (i = 0; i < MAX_TRACKS; i++) {
    var t = trackBank.getItemAt(i);
    watchChannel(t);
    for (j = 0; j < MAX_SENDS; j++) {
      t.sendBank().getItemAt(j).markInterested();
      t.sendBank().getItemAt(j).displayedValue().markInterested();
    }
    t.clipLauncherSlotBank().getItemAt(0).hasContent().markInterested();
    trackDevices.push(watchDevices(t.createDeviceBank(MAX_DEVICES)));
  }
  for (i = 0; i < MAX_FX; i++) {
    var f = fxBank.getItemAt(i);
    watchChannel(f);
    fxDevices.push(watchDevices(f.createDeviceBank(MAX_DEVICES)));
  }
  watchDevices(masterDevices, MAX_MASTER_DEVICES);
  for (i = 0; i < MAX_MARKERS; i++) {
    var m = markers.getItemAt(i);
    m.exists().markInterested();
    m.name().markInterested();
    m.position().markInterested();
  }
  clipTrack.name().markInterested();
  clipTrack.name().addValueObserver(function () { lengthSeen = false; });
  // The clip's range: Bitwig drops sets on values nobody subscribed to, so
  // these must be observed from init() for Build to change a clip's length.
  var ranges = [clip.getPlayStart(), clip.getPlayStop(), clip.getLoopStart(), clip.getLoopLength()];
  for (i = 0; i < ranges.length; i++) {
    ranges[i].markInterested();
    ranges[i].addValueObserver(function () { lengthSeen = true; });
  }
  clip.isLoopEnabled().markInterested();
  clip.getShuffle().markInterested();
  clip.addStepDataObserver(function (x, y, state) {
    var key = x + ":" + y;
    if (state === 2) {
      if (!noteStarts[key]) { noteStarts[key] = true; noteStartCount++; }
    } else if (noteStarts[key]) {
      delete noteStarts[key];
      noteStartCount--;
    }
  });

  var prefs = host.getPreferences();
  var section = SCORE.title;
  prefs.getSignalSetting("Build the track", section, "Build").addSignalObserver(function () { run("build", buildSteps()); });
  prefs.getSignalSetting("Check clip lengths", section, "Lengths").addSignalObserver(function () { run("lengths", lengthSteps()); });
  prefs.getSignalSetting("Record scene 1 into the arranger", section, "Record").addSignalObserver(function () { run("record", recordSteps()); });
  prefs.getSignalSetting("Stop and disarm", section, "Stop").addSignalObserver(stopAndDisarm);

  say("version " + VERSION + " loaded");
  log("ready: " + SCORE.tracks.length + " parts, " + SCORE.lengthBeats + " beats (" + SCORE.lengthBeats / 4 + " bars) at " +
      SCORE.tempo + " bpm. Press Build under this controller in Settings > Controllers.");
}

function watchChannel(t) {
  t.exists().markInterested();
  t.name().markInterested();
  t.volume().markInterested();
  t.volume().displayedValue().markInterested();
  t.pan().markInterested();
  t.color().markInterested();
}

function watchDevices(bank, size) {
  size = size || MAX_DEVICES;
  for (var i = 0; i < size; i++) {
    bank.getItemAt(i).exists().markInterested();
    bank.getItemAt(i).name().markInterested();
  }
  return bank;
}

function flush() {}

function exit() { log("bye"); }

// ---------------------------------------------------------------- the runner

function steps() { return Math.round(SCORE.lengthBeats / SCORE.stepSize); }

function later(ms, fn) {
  host.scheduleTask(function () {
    try { fn(); } catch (e) { host.errorln(TAG + "error: " + e); running = false; }
  }, ms);
}

// Run steps one after another. A step is function(next, fail).
function run(label, list) {
  if (running) { say("still busy with the last action, wait for it to finish"); return; }
  running = true;
  var i = 0;
  log(label + ": " + list.length + " steps");
  function fail(msg) {
    running = false;
    host.errorln(TAG + label + " stopped: " + msg);
    host.showPopupNotification(SCORE.title + ": " + label + " stopped: " + msg);
  }
  function next() {
    if (i >= list.length) { running = false; say(label + " done"); return; }
    var step = list[i++];
    later(0, function () {
      try { step(next, fail); } catch (e) { fail(String(e)); }
    });
  }
  next();
}

// Poll until test() is true, then ok(); after timeout ms, fail().
function waitFor(what, test, timeout, ok, fail) {
  var waited = 0;
  function poll() {
    var done = false;
    try { done = test(); } catch (e) { done = false; }
    if (done) { ok(); return; }
    if (waited >= timeout) { fail("timed out after " + timeout + " ms waiting for " + what); return; }
    waited += POLL_MS;
    later(POLL_MS, poll);
  }
  poll();
}

// ---------------------------------------------------------------- lookups

function count(bank, size) {
  var n = 0;
  for (var i = 0; i < size; i++) if (bank.getItemAt(i).exists().get()) n++;
  return n;
}

function find(bank, size, name) {
  for (var i = 0; i < size; i++) {
    var t = bank.getItemAt(i);
    if (t.exists().get() && t.name().get() === name) return i;
  }
  return -1;
}

function trackIndex(name) { return find(trackBank, MAX_TRACKS, name); }
function fxIndex(name) { return find(fxBank, MAX_FX, name); }
function markerCount() { return count(markers, MAX_MARKERS); }

function markerNamed(name) {
  for (var i = 0; i < MAX_MARKERS; i++) {
    var m = markers.getItemAt(i);
    if (m.exists().get() && m.name().get() === name) return m;
  }
  return null;
}

function near(a, b) { return Math.abs(a - b) < 0.01; }

function basename(path) { return path.replace(/^.*\//, "").replace(/\.bwpreset$/, ""); }

// ---------------------------------------------------------------- build

function buildSteps() {
  var list = [];
  list.push(function (next) { lengthReport = []; next(); });
  list.push(setTempo);
  list.push(setGroove);
  var i;
  for (i = 0; i < SCORE.fx.length; i++) list = list.concat(ensureTrack(SCORE.fx[i], true));
  for (i = 0; i < SCORE.tracks.length; i++) list = list.concat(ensureTrack(SCORE.tracks[i], false));
  list = list.concat(mixSteps());
  list.push(masterGlue);
  for (i = 0; i < SCORE.tracks.length; i++) list = list.concat(writeClip(SCORE.tracks[i]));
  list.push(reportLengths);
  list = list.concat(markerSteps());
  list.push(function (next) {
    transport.setPosition(0);
    log("built " + SCORE.tracks.length + " tracks. Next: press Record, or launch scene 1 with arranger record armed.");
    next();
  });
  return list;
}

function setTempo(next, fail) {
  log("tempo " + SCORE.tempo + " bpm, 4/4");
  transport.tempo().value().setRaw(SCORE.tempo);
  transport.timeSignature().set("4/4");
  waitFor("the tempo", function () { return near(transport.tempo().value().getRaw(), SCORE.tempo); }, 3000, next, fail);
}

// The groove: on, 16th shuffle, the amount by what Bitwig displays. Nothing
// here stops the build; it logs what it got.
function setGroove(next) {
  groove.getEnabled().set(1);
  groove.getShuffleRate().set(SCORE.groove.rate === "1/16" ? 1 : 0);
  later(200, function () {
    log("groove " + groove.getEnabled().displayedValue().get() + ", shuffle rate " + groove.getShuffleRate().displayedValue().get());
    setByDisplay(groove.getShuffleAmount(), SCORE.groove.shuffle, 0.25, 0.22, "shuffle amount", function (ok, shown) {
      log("shuffle amount " + shown + (ok ? "" : " (wanted " + SCORE.groove.shuffle + " %)"));
      next();
    });
  });
}

// Find a track by name or create it, name and colour it, load its preset if it
// has no device yet, then its inserts.
function ensureTrack(spec, isFx) {
  var bank = isFx ? fxBank : trackBank;
  var size = isFx ? MAX_FX : MAX_TRACKS;
  var devices = isFx ? fxDevices : trackDevices;
  var kind = isFx ? "return track" : "track";
  var index = -1;

  function create(next, fail) {
    index = find(bank, size, spec.name);
    if (index >= 0) { log(kind + " '" + spec.name + "' exists at " + (index + 1) + ", reusing it"); colour(); next(); return; }
    var before = count(bank, size);
    if (before >= size) { fail("more than " + size + " " + kind + "s; remove some"); return; }
    log("creating " + kind + " '" + spec.name + "'");
    if (isFx) app.createEffectTrack(-1); else app.createInstrumentTrack(-1);
    waitFor("the new " + kind, function () { return count(bank, size) === before + 1; }, 5000, function () {
      index = before;           // -1 appends: the new track is the last one
      bank.getItemAt(index).name().set(spec.name);
      waitFor("the name '" + spec.name + "'", function () { return bank.getItemAt(index).name().get() === spec.name; }, 3000, function () {
        colour();
        next();
      }, fail);
    }, fail);
  }

  function colour() {
    if (spec.color) bank.getItemAt(index).color().set(spec.color[0], spec.color[1], spec.color[2]);
  }

  function load(next, fail) {
    var d = devices[index];
    if (d.getItemAt(0).exists().get()) { log("'" + spec.name + "' already has " + d.getItemAt(0).name().get() + ", keeping it"); next(); return; }
    log("loading " + basename(spec.preset) + " on '" + spec.name + "'");
    bank.getItemAt(index).startOfDeviceChainInsertionPoint().insertFile(spec.preset);
    waitFor("the preset on '" + spec.name + "'", function () { return d.getItemAt(0).exists().get(); }, 15000, function () {
      log("'" + spec.name + "' has " + d.getItemAt(0).name().get());
      next();
    }, fail);
  }

  // Inserts after the instrument, one at a time; a track that already has
  // enough devices keeps them.
  function inserts(next, fail) {
    var list = spec.inserts || [];
    var k = count(devices[index], MAX_DEVICES) - 1;
    function more() {
      if (k >= list.length) { next(); return; }
      var before = count(devices[index], MAX_DEVICES);
      if (before >= MAX_DEVICES) { log("'" + spec.name + "' has no room for more devices"); next(); return; }
      log("adding " + basename(list[k]) + " after the instrument on '" + spec.name + "'");
      bank.getItemAt(index).endOfDeviceChainInsertionPoint().insertFile(list[k]);
      waitFor(basename(list[k]) + " on '" + spec.name + "'", function () { return count(devices[index], MAX_DEVICES) === before + 1; }, 15000, function () {
        k++;
        more();
      }, fail);
    }
    if (list.length && k >= list.length) log("'" + spec.name + "' already has its inserts");
    more();
  }

  return [create, load, inserts];
}

// ---------------------------------------------------------------- mix in dB

// Bitwig's faders read in dB. The first guess is its cubic taper (0 dB near
// 0.794 of the range); then we bisect on what Bitwig displays until it's
// within tol.
function dbGuess(db) {
  var x = Math.pow(Math.pow(10, db / 20) / 2, 1 / 3);
  return Math.max(0, Math.min(1, x));
}

function parseNumber(s) {
  if (s === null || s === undefined) return NaN;
  s = String(s);
  if (/-\s*inf|-∞/i.test(s)) return -200;
  var m = s.match(/[-+]?\d+(?:[.,]\d+)?/);
  return m ? parseFloat(m[0].replace(",", ".")) : NaN;
}

// Set a parameter so that its displayed number reads target. done(ok, shown).
function setByDisplay(param, target, guess, tol, what, done) {
  var lo = 0, hi = 1, x = guess, tries = 0, shown = "";
  function attempt() {
    tries++;
    var before = param.displayedValue().get();
    param.set(x);
    var waited = 0;
    function poll() {
      var now = param.displayedValue().get();
      if ((now !== before || waited >= 400) && !isNaN(parseNumber(now))) { check(now); return; }
      if (waited >= 1200) { check(now); return; }
      waited += POLL_MS;
      later(POLL_MS, poll);
    }
    later(POLL_MS, poll);
  }
  function check(now) {
    shown = now;
    var v = parseNumber(now);
    if (isNaN(v)) { log(what + ": can't read '" + now + "', left at " + Math.round(x * 1000) / 1000); done(false, now); return; }
    if (Math.abs(v - target) <= tol) { done(true, now); return; }
    if (tries >= 14) { done(false, now); return; }
    if (v < target) lo = x; else hi = x;
    x = (lo + hi) / 2;
    attempt();
  }
  attempt();
}

function mixSteps() {
  var list = [];
  var i;
  for (i = 0; i < SCORE.fx.length; i++) list.push(mixFx(SCORE.fx[i]));
  for (i = 0; i < SCORE.tracks.length; i++) list.push(mixTrack(SCORE.tracks[i]));
  return list;
}

function mixFx(spec) {
  return function (next, fail) {
    var f = fxIndex(spec.name);
    if (f < 0) { fail("return track '" + spec.name + "' is missing"); return; }
    var v = fxBank.getItemAt(f).volume();
    setByDisplay(v, spec.db, dbGuess(spec.db), 0.3, spec.name + " fader", function (ok, shown) {
      log("'" + spec.name + "' fader " + shown + (ok ? "" : " (wanted " + spec.db + " dB)"));
      next();
    });
  };
}

function mixTrack(spec) {
  return function (next, fail) {
    var t = trackIndex(spec.name);
    if (t < 0) { fail("track '" + spec.name + "' is missing"); return; }
    var track = trackBank.getItemAt(t);
    track.pan().set(spec.pan);
    var jobs = [{ param: track.volume(), db: spec.db, what: spec.name + " fader" }];
    for (var j = 0; j < SCORE.fx.length; j++) {
      var name = SCORE.fx[j].name;
      var f = fxIndex(name);
      if (f < 0 || f >= MAX_SENDS) { log("no send to '" + name + "' from '" + spec.name + "'"); continue; }
      var send = track.sendBank().getItemAt(f);
      if (spec.sends.hasOwnProperty(name)) jobs.push({ param: send, db: spec.sends[name], what: spec.name + " > " + name });
      else send.set(0);
    }
    var k = 0, report = [];
    function more() {
      if (k >= jobs.length) { log("'" + spec.name + "': " + report.join(", ") + ", pan " + spec.pan); next(); return; }
      var job = jobs[k++];
      setByDisplay(job.param, job.db, dbGuess(job.db), 0.3, job.what, function (ok, shown) {
        report.push((k === 1 ? "fader " : job.what.replace(spec.name + " > ", "") + " ") + shown + (ok ? "" : " (wanted " + job.db + ")"));
        more();
      });
    }
    more();
  };
}

function masterGlue(next, fail) {
  for (var i = 0; i < MAX_MASTER_DEVICES; i++) {
    var d = masterDevices.getItemAt(i);
    if (d.exists().get() && d.name().get() === SCORE.master.device) {
      log("master already has " + SCORE.master.device + ", keeping it");
      next();
      return;
    }
  }
  var before = count(masterDevices, MAX_MASTER_DEVICES);
  log("loading " + basename(SCORE.master.preset) + " on the master");
  master.endOfDeviceChainInsertionPoint().insertFile(SCORE.master.preset);
  waitFor("the master compressor", function () { return count(masterDevices, MAX_MASTER_DEVICES) === before + 1; }, 15000, next, fail);
}

// ---------------------------------------------------------------- clips

// Replace the track's scene-1 clip with the part.
function writeClip(spec) {
  var index = -1, slots = null, slot = null;

  function clear(next, fail) {
    index = trackIndex(spec.name);
    if (index < 0) { fail("track '" + spec.name + "' is missing"); return; }
    slots = trackBank.getItemAt(index).clipLauncherSlotBank();
    slot = slots.getItemAt(0);
    if (!slot.hasContent().get()) { next(); return; }
    log("replacing the clip on '" + spec.name + "'");
    slots.deleteClip(0);
    waitFor("the old clip to go", function () { return !slot.hasContent().get(); }, 3000, next, fail);
  }

  function create(next, fail) {
    slots.createEmptyClip(0, SCORE.lengthBeats);
    waitFor("a clip on '" + spec.name + "'", function () { return slot.hasContent().get(); }, 3000, next, fail);
  }

  function select(next, fail) {
    selectClip(slot, spec.name, next, fail);
  }

  function size(next) {
    fitLength(spec.name, true, function (ok) {
      if (!ok) log("'" + spec.name + "' is still " + describeLength() + " before writing");
      next();
    });
  }

  function write(next) {
    clip.setStepSize(SCORE.stepSize);
    clip.scrollToKey(0);
    clip.scrollToStep(0);
    clip.clearSteps();
    later(150, function () {
      var notes = spec.notes;
      for (var i = 0; i < notes.length; i++) {
        var n = notes[i];     // [start beat, pitch, velocity, duration beats]
        clip.setStep(0, Math.round(n[0] / SCORE.stepSize), n[1], n[2], n[3]);
      }
      clip.setName(spec.name);
      clip.getShuffle().set(!!spec.shuffle);
      var starts = {};
      for (i = 0; i < notes.length; i++) starts[Math.round(notes[i][0] / SCORE.stepSize) + ":" + notes[i][1]] = true;
      var expected = Object.keys(starts).length;
      waitFor(expected + " notes on '" + spec.name + "'", function () {
        return clipTrack.name().get() === spec.name && noteStartCount === expected;
      }, 10000, function () {
        log("'" + spec.name + "': " + expected + " notes written");
        confirm();
      }, function () {
        log("'" + spec.name + "': wrote " + expected + " notes, the editor reports " + noteStartCount + " (check this clip)");
        confirm();
      });
      // Writing notes must not have shortened it; set it again if it did.
      function confirm() {
        fitLength(spec.name, false, function (ok) {
          var line = spec.name + ": " + describeLength();
          lengthReport.push({ line: line, ok: ok });
          if (ok) log(line + " (confirmed)"); else host.errorln(TAG + line + ": NOT the full " + SCORE.lengthBeats + " beats");
          next();
        });
      }
    });
  }

  return [clear, create, select, size, write];
}

// ---------------------------------------------------------------- clip length

var lengthReport = [];

function selectClip(slot, name, next, fail) {
  slot.select();
  slot.showInEditor();
  waitFor("the editor to show '" + name + "'", function () { return clipTrack.name().get() === name; }, 3000, function () {
    waitFor("the clip range of '" + name + "'", function () { return lengthSeen; }, 600, settle, settle);
  }, fail);
  function settle() { later(150, next); }
}

function clipLength() {
  if (clip.isLoopEnabled().get()) return clip.getLoopStart().get() + clip.getLoopLength().get();
  return clip.getPlayStop().get() - clip.getPlayStart().get();
}

function describeLength() {
  var beats = Math.round(clipLength() * 1000) / 1000;
  return beats + " beats (" + Math.round(beats / 4 * 100) / 100 + " bars" +
    (clip.isLoopEnabled().get() ? ", looping " + clip.getLoopLength().get() : ", play stop " + clip.getPlayStop().get()) + ")";
}

function plays() {
  return !clip.isLoopEnabled().get() && near(clip.getPlayStart().get(), 0) && clip.getPlayStop().get() >= SCORE.lengthBeats - 0.01;
}

function fullLength() {
  var L = SCORE.lengthBeats;
  return near(clip.getPlayStart().get(), 0) && clip.getPlayStop().get() >= L - 0.01 &&
    near(clip.getLoopStart().get(), 0) && clip.getLoopLength().get() >= L - 0.01 &&
    !clip.isLoopEnabled().get();
}

// Set the clip's play range and loop to the full length, read it back, retry;
// if Bitwig won't take it and the clip is still empty, double it with
// duplicateContent until it's long enough, then try again. done(ok).
function fitLength(name, canDouble, done) {
  var L = SCORE.lengthBeats, attempt = 0, doublings = 0;
  function set() {
    attempt++;
    clip.getLoopStart().set(0);
    clip.getLoopLength().set(L);
    clip.getPlayStart().set(0);
    clip.getPlayStop().set(L);
    clip.isLoopEnabled().set(false);
    waitFor("the length of '" + name + "'", fullLength, 700, function () {
      if (attempt > 1 || doublings) log("'" + name + "' took " + attempt + " tries" + (doublings ? " and " + doublings + " doublings" : ""));
      done(true);
    }, retry);
  }
  function retry() {
    log("'" + name + "' reads " + describeLength() + " after try " + attempt);
    if (attempt < 4) { set(); return; }
    if (canDouble && doublings < 10 && Math.max(clip.getPlayStop().get(), clip.getLoopLength().get()) < L - 0.01) {
      double();
      return;
    }
    done(plays());
  }
  function double() {
    var before = Math.max(clip.getPlayStop().get(), clip.getLoopLength().get());
    doublings++;
    log("'" + name + "': doubling the empty clip (" + before + " beats)");
    clip.isLoopEnabled().set(true);
    clip.duplicateContent();
    waitFor("the clip to double", function () {
      return Math.max(clip.getPlayStop().get(), clip.getLoopLength().get()) > before + 0.01;
    }, 1500, function () {
      if (Math.max(clip.getPlayStop().get(), clip.getLoopLength().get()) < L - 0.01 && doublings < 10) { double(); return; }
      attempt = 0;
      set();
    }, function () {
      log("'" + name + "': duplicateContent didn't change the length either");
      done(false);
    });
  }
  set();
}

function lengthSteps() {
  var list = [function (next) { lengthReport = []; next(); }];
  for (var i = 0; i < SCORE.tracks.length; i++) list.push(checkLength(SCORE.tracks[i]));
  list.push(reportLengths);
  return list;
}

function checkLength(spec) {
  return function (next, fail) {
    var t = trackIndex(spec.name);
    if (t < 0) { lengthReport.push({ line: spec.name + ": no track", ok: false }); next(); return; }
    var slot = trackBank.getItemAt(t).clipLauncherSlotBank().getItemAt(0);
    if (!slot.hasContent().get()) { lengthReport.push({ line: spec.name + ": no clip", ok: false }); next(); return; }
    selectClip(slot, spec.name, function () {
      var ok = plays();
      lengthReport.push({ line: spec.name + ": " + describeLength() + (ok ? "" : "  <-- short"), ok: ok });
      log(lengthReport[lengthReport.length - 1].line);
      next();
    }, fail);
  };
}

function reportLengths(next) {
  var short = [], lines = [];
  for (var i = 0; i < lengthReport.length; i++) {
    lines.push(lengthReport[i].line);
    if (!lengthReport[i].ok) short.push(lengthReport[i].line);
  }
  log("clip lengths:\n  " + lines.join("\n  "));
  say(short.length ? short.length + " clip(s) short: " + short.join("; ")
                   : "all " + lines.length + " clips play " + SCORE.lengthBeats + " beats (" + SCORE.lengthBeats / 4 + " bars), e.g. " + lines[0]);
  next();
}

// ---------------------------------------------------------------- cue markers

function markerSteps() {
  var list = [];
  for (var i = 0; i < SCORE.cues.length; i++) list.push(addMarker(SCORE.cues[i]));
  list.push(function (next) { transport.setPosition(0); next(); });
  return list;
}

function addMarker(cue) {
  return function (next, fail) {
    var existing = markerNamed(cue.name);
    if (existing) {
      existing.position().set(cue.beat);
      log("cue marker '" + cue.name + "' at bar " + cue.bar);
      next();
      return;
    }
    var before = markerCount();
    transport.setPosition(cue.beat);
    waitFor("the playhead at " + cue.beat, function () { return near(transport.playPosition().get(), cue.beat); }, 1500, add, add);

    function add() {
      transport.addCueMarkerAtPlaybackPosition();
      waitFor("a new cue marker", function () { return markerCount() === before + 1; }, 3000, function () {
        var named = false;
        for (var i = 0; i < MAX_MARKERS && !named; i++) {
          var m = markers.getItemAt(i);
          if (m.exists().get() && near(m.position().get(), cue.beat) && !isCue(m.name().get())) {
            m.name().set(cue.name);
            named = true;
          }
        }
        if (!named) {
          var best = null, dist = 1e9;
          for (i = 0; i < MAX_MARKERS; i++) {
            var c = markers.getItemAt(i);
            if (!c.exists().get() || isCue(c.name().get())) continue;
            var d = Math.abs(c.position().get() - cue.beat);
            if (d < dist) { dist = d; best = c; }
          }
          if (best) { best.position().set(cue.beat); best.name().set(cue.name); named = true; }
        }
        log(named ? "cue marker '" + cue.name + "' at bar " + cue.bar
                  : "added a cue marker at bar " + cue.bar + " but couldn't name it '" + cue.name + "'");
        next();
      }, fail);
    }
  };
}

function isCue(name) {
  for (var i = 0; i < SCORE.cues.length; i++) if (SCORE.cues[i].name === name) return true;
  return false;
}

// ---------------------------------------------------------------- record into the arranger

var savedPreRoll = null;

function recordSteps() {
  return [
    function check(next, fail) {
      for (var i = 0; i < SCORE.tracks.length; i++) {
        var t = trackIndex(SCORE.tracks[i].name);
        if (t < 0) { fail("track '" + SCORE.tracks[i].name + "' is missing; press Build first"); return; }
        if (!trackBank.getItemAt(t).clipLauncherSlotBank().getItemAt(0).hasContent().get()) {
          fail("'" + SCORE.tracks[i].name + "' has no clip in scene 1; press Build first");
          return;
        }
      }
      next();
    },
    function arm(next, fail) {
      transport.stop();
      savedPreRoll = transport.preRoll().get();
      transport.preRoll().set("none");
      transport.setPosition(0);
      transport.isArrangerRecordEnabled().set(true);
      log("arranger record armed at bar 1 (pre-roll was " + savedPreRoll + ")");
      waitFor("arranger record", function () {
        return transport.isArrangerRecordEnabled().get() && !transport.isPlaying().get();
      }, 3000, next, fail);
    },
    function launch(next, fail) {
      log("launching scene 1");
      sceneBank.getScene(0).launch();
      later(300, function () {
        if (!transport.isPlaying().get()) transport.play();
        waitFor("the transport to play", function () { return transport.isPlaying().get(); }, 3000, next, fail);
      });
    },
    function finish(next, fail) {
      var end = SCORE.lengthBeats + 0.5;
      var seconds = Math.ceil(end * 60 / SCORE.tempo) + 30;
      log("recording " + SCORE.lengthBeats + " beats (about " + Math.round(SCORE.lengthBeats * 60 / SCORE.tempo) + " s)");
      waitFor("the end of the track", function () {
        return !transport.isPlaying().get() || transport.playPosition().get() >= end;
      }, seconds * 1000, function () {
        stopAndDisarm();
        log("recorded into the arranger. Check the new clips from bar 1, then File > Export Audio.");
        next();
      }, function (msg) { stopAndDisarm(); fail(msg); });
    }
  ];
}

function stopAndDisarm() {
  transport.stop();
  transport.isArrangerRecordEnabled().set(false);
  transport.returnToArrangement();
  if (savedPreRoll !== null) { transport.preRoll().set(savedPreRoll); savedPreRoll = null; }
  transport.setPosition(0);
  log("stopped, arranger record off, tracks back on the arrangement");
}
